### ISSUE TITLE
关于配置使用

### ISSUE THREAD

**Issue by luoxiao** [lizhuangs/picgo-plugin-gitee-uploader#1]
你好，我没看懂gitee插件怎么使用。
github倒是可以配置token，直接使用，
这个插件呢

**Comment by luoxiao** [comment]
麻烦告知下哈，谢谢。

**Comment by luoxiao** [comment]
没有看到GUI，对应的配置哦！

**Comment by lizhuangs** [comment]
不好意思，最近忙没看，你更新最新版本1.0.3看一下。

**Comment by luoxiao** [comment]
哈哈，插件列表显示出来了，谢谢。
再提个小小建议，发现自定义url这一栏 填了，customURL不生效。

**Comment by lizhuangs** [comment]
好的，回头我再看下。

**Comment by lizhuangs** [comment]
你看下是否好了，之前没用到这个，也就没注意了。

**Comment by luoxiao** [comment]
哈哈，谢谢，一切都正常使用。
感恩，感谢！

**Comment by A-little-bit-of-data** [comment]
> 哈哈，谢谢，一切都正常使用。
> 感恩，感谢！

请问一下这个是怎么使用的，我都配置好了，但是还是不能上传？

**Comment by lizhuangs** [comment]
> > 哈哈，谢谢，一切都正常使用。
> > 感恩，感谢！
> 
> 请问一下这个是怎么使用的，我都配置好了，但是还是不能上传？

设置页面有日志，你可以点击自己看一看，不能上传一般是配置的不对。尤其是仓库和token这2个值。
