### ISSUE TITLE
picGo2.2.2版本无法搜索到此版本

### ISSUE THREAD

**Issue by xkf001** [lizhuangs/picgo-plugin-gitee-uploader#11]
**描述bug**
系统和软件等环境的版本
具体的bug信息.

**步骤**
具体步骤

**截图**
如果有截图的话

**Additional context**

**Comment by lizhuangs** [comment]
测试搜索gitee即可。可能是你的网络问题，建议多试几次。

**Comment by oucliut** [comment]
> 测试搜索gitee即可。可能是你的网络问题，建议多试几次。

您好，这个插件用picgo一直安装不上，离线安装的时候导入也不成功，谢谢！
